import { default as EM } from './event-manager';

const ENTITY = {
  MOVE: 'ENTITY_MOVE',
  CREATED: 'ENTITY_CREATED',
  DESTROYED: 'ENTITY_DESTROYED',
};

const TANK = {
  SHOOT: 'TANK_SHOOT',
  DESTROYED: 'TANK_DESTROYED',
  AWARD_TANK_HIT: 'AWARD_TANK_HIT',
  ALLY_TANK_DESTROYED: 'ALLY_TANK_DESTROYED',
  ENEMY_TANK_DESTROYED: 'ENEMY_TANK_DESTROYED',
  LAST_ENEMY_TANK_DESTROYED: 'LAST_ENEMY_TANK_DESTROYED',
};

const MINE = {
  ALLY_OVER: 'ALLY_MINE_TICK_OVER',
  ENEMY_OVER: 'ENEMY_MIN_TICK_OVER',
};

const EXPLOSION = {
  ENEMY_YANK_EXPLOSION: 'ENEMY_YANK_EXPLOSION',
};

const BASE = {
  DESTROY: 'BASE_DESTROY',
};

const CONSTRUCT = {
  BUILD: 'CONSTRUCT_BUILD',
};

const BULLET = {
  CREATE: 'BULLET_CREATE',
  DESTROYED: 'BULLET_DESTROYED',
};

const AWARD = {
  PICKED: 'AWARD_PICKED',
  DESTROYED: 'AWARD_DESTROYED',
  ENEMY_PICK_SPADE: 'ENEMY_PICK_SPADE',
  ENEMY_PICK_BOMB: 'ENEMY_PICK_BOMB',
  ENEMY_PICK_MINE: 'ENEMY_PICK_MINE',
  ALLY_PICK_SPADE: 'ALLY_PICK_SPADE',
  ALLY_PICK_BOMB: 'ALLY_PICK_BOMB',
  ALLY_PICK_MINE: 'ALLY_PICK_MINE',
};

const COLLISION = {
  BORDER: 'COLLISION_BORDER',
  ENTITY: 'COLLISION_ENTITY',
};

const KEYBOARD = {
  PRESS: 'KEY_PRESS',
  RELEASE: 'KEY_RELEASE',
};

const CONTROL = {
  P1: {
    UP: 'P1_UP',
    RIGHT: 'P1_RIGHT',
    DOWN: 'P1_DOWN',
    LEFT: 'P1_LEFT',
    A: 'P1_A',
    B: 'P1_B',
    SELECT: 'P1_SELECT',
    START: 'P1_START',
  },
  P2: {
    UP: 'P2_UP',
    RIGHT: 'P2_RIGHT',
    DOWN: 'P2_DOWN',
    LEFT: 'P2_LEFT',
    A: 'P2_A',
    B: 'P2_B',
  },
};

const GAME = {
  PAUSE: 'GAME_PAUSE',
  OVER: 'GAME_OVER',
  DEFEAT: 'GAME_DEFEAT',
};

export default {
  EM,
  BASE,
  MINE,
  KEYBOARD,
  EXPLOSION,
  AWARD,
  CONSTRUCT,
  ENTITY,
  TANK,
  BULLET,
  COLLISION,
  CONTROL,
  GAME,
};
